#!/usr/bin/env bun
import { readdirSync, readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";

interface ChainDeployments {
  [contractName: string]: {
    address: string;
    abi: unknown[];
  };
}

interface AllDeployments {
  [chainId: string]: ChainDeployments;
}

interface DeploymentFileEntry {
  address: string;
}

interface DeploymentFile {
  chainId?: string;
  [contractName: string]: unknown;
}

const DEPLOYMENTS_DIR = join(process.cwd(), "deployments");
const OUT_DIR = join(process.cwd(), "out");

function loadArtifact(contractName: string): { abi: unknown[] } | null {
  const artifactPath = join(
    OUT_DIR,
    `${contractName}.sol`,
    `${contractName}.json`,
  );

  if (!existsSync(artifactPath)) {
    return null;
  }

  return JSON.parse(readFileSync(artifactPath, "utf-8"));
}

function isAddress(value: unknown): value is string {
  return typeof value === "string" && /^0x[a-fA-F0-9]{40}$/.test(value);
}

function decodeHexJson(value: string): DeploymentFileEntry | null {
  if (!value.startsWith("0x")) {
    return null;
  }

  try {
    const decoded = Buffer.from(value.slice(2), "hex").toString("utf-8");
    const parsed = JSON.parse(decoded) as unknown;
    if (
      typeof parsed === "object" &&
      parsed !== null &&
      "address" in parsed &&
      isAddress((parsed as Record<string, unknown>).address)
    ) {
      return { address: (parsed as Record<string, string>).address };
    }
  } catch {
    return null;
  }

  return null;
}

function extractDeploymentAddress(value: unknown): string | null {
  if (typeof value === "object" && value !== null && "address" in value) {
    const address = (value as Record<string, unknown>).address;
    return isAddress(address) ? address : null;
  }

  if (typeof value === "string") {
    if (isAddress(value)) {
      return value;
    }

    return decodeHexJson(value)?.address ?? null;
  }

  return null;
}

function generateTsContent(allDeployments: AllDeployments): string {
  const chainIds = Object.keys(allDeployments);

  let content = `// Auto-generated by generateTsAbis.ts
// Do not edit manually - regenerate after deployment

export const deployedContracts = ${JSON.stringify(allDeployments, null, 2)} as const;

export type ChainId = ${chainIds.map((id) => `"${id}"`).join(" | ")};

`;

  // Add contract name types for each chain (prefix with Chain to avoid numeric type names)
  for (const chainId of chainIds) {
    const contractNames = Object.keys(allDeployments[chainId]);
    if (contractNames.length > 0) {
      const safeName = `Chain${chainId.replace(/-/g, "")}`;
      content += `export type ${safeName}ContractName = ${contractNames
        .map((n) => `"${n}"`)
        .join(" | ")};\n`;
    }
  }

  content += `
// Helper types
export type ContractDeployment = {
  address: \`0x\${string}\`;
  abi: readonly unknown[];
};

// Helper to access deployments with proper typing
function getChainDeployments(chainId: ChainId): Record<string, { address: string; abi: unknown[] }> | undefined {
  return (deployedContracts as unknown as Record<string, Record<string, { address: string; abi: unknown[] }>>)[chainId];
}

export function getContract(chainId: ChainId, contractName: string): ContractDeployment {
  const chain = getChainDeployments(chainId);
  const contract = chain?.[contractName];
  if (!contract) {
    throw new Error(\`Contract \${contractName} not found on chain \${chainId}\`);
  }
  return { address: contract.address as \`0x\${string}\`, abi: contract.abi as readonly unknown[] };
}

export function getContractAddress(chainId: ChainId, contractName: string): \`0x\${string}\` {
  return getContract(chainId, contractName).address;
}
`;

  return content;
}

export function generateTsAbis(): boolean {
  console.log("\n📦 Generating TypeScript ABIs...\n");

  if (!existsSync(DEPLOYMENTS_DIR)) {
    console.log("❌ No deployments directory found. Run deployment first.");
    return false;
  }

  const deploymentFiles = readdirSync(DEPLOYMENTS_DIR)
    .filter((fileName) => fileName.endsWith(".json"));

  if (deploymentFiles.length === 0) {
    console.log("❌ No deployment records found.");
    return false;
  }

  const allDeployments: AllDeployments = {};

  for (const fileName of deploymentFiles) {
    const chainId = fileName.replace(/\.json$/, "");
    console.log(`Processing chain ${chainId}...`);

    const filePath = join(DEPLOYMENTS_DIR, fileName);
    const deploymentFile = JSON.parse(
      readFileSync(filePath, "utf-8"),
    ) as DeploymentFile;
    const deployments: ChainDeployments = {};

    for (const [contractName, rawValue] of Object.entries(deploymentFile)) {
      if (contractName === "chainId") {
        continue;
      }

      const contractAddress = extractDeploymentAddress(rawValue);
      if (!contractAddress) {
        console.log(`  ⚠️  Invalid deployment entry for ${contractName}`);
        continue;
      }

      const artifact = loadArtifact(contractName);
      if (!artifact) {
        console.log(`  ⚠️  Artifact not found for ${contractName}`);
        continue;
      }

      deployments[contractName] = {
        address: contractAddress,
        abi: artifact.abi,
      };

      console.log(`  ✅ ${contractName}: ${contractAddress}`);
    }

    if (Object.keys(deployments).length > 0) {
      allDeployments[chainId] = deployments;
    }
  }

  if (Object.keys(allDeployments).length === 0) {
    console.log("\n❌ No deployments found to export.");
    return false;
  }

  // Generate TypeScript file
  const tsContent = generateTsContent(allDeployments);

  // Write to contracts package
  const contractsOutputPath = join(process.cwd(), "deployedContracts.ts");
  writeFileSync(contractsOutputPath, tsContent);
  console.log(`\n✅ Generated: ${contractsOutputPath}`);

  // Also write to React Native app's lib/blockchain directory
  const appOutputPath = join(
    process.cwd(),
    "..",
    "..",
    "lib",
    "blockchain",
    "deployedContracts.ts",
  );
  writeFileSync(appOutputPath, tsContent);
  console.log(`✅ Generated: ${appOutputPath}\n`);

  return true;
}

// Run if executed directly
if (import.meta.main) {
  generateTsAbis();
}
