#!/usr/bin/env bun
import { readdirSync, readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";

interface Transaction {
  transactionType: string;
  contractName: string;
  contractAddress: string;
  arguments?: string;
}

interface BroadcastRun {
  transactions: Transaction[];
}

interface ChainDeployments {
  [contractName: string]: {
    address: string;
    abi: unknown[];
  };
}

interface AllDeployments {
  [chainId: string]: ChainDeployments;
}

const BROADCAST_DIR = join(process.cwd(), "broadcast");
const OUT_DIR = join(process.cwd(), "out");

function findLatestRunFile(chainId: string): string | null {
  const chainBroadcastDir = join(BROADCAST_DIR, "Deploy.s.sol", chainId);

  if (!existsSync(chainBroadcastDir)) {
    return null;
  }

  const runFiles = readdirSync(chainBroadcastDir)
    .filter((f) => f.startsWith("run-") && f.endsWith(".json"))
    .sort()
    .reverse();

  return runFiles.length > 0 ? join(chainBroadcastDir, runFiles[0]) : null;
}

function loadArtifact(contractName: string): { abi: unknown[] } | null {
  const artifactPath = join(
    OUT_DIR,
    `${contractName}.sol`,
    `${contractName}.json`,
  );

  if (!existsSync(artifactPath)) {
    return null;
  }

  return JSON.parse(readFileSync(artifactPath, "utf-8"));
}

function generateTsContent(allDeployments: AllDeployments): string {
  const chainIds = Object.keys(allDeployments);

  let content = `// Auto-generated by generateTsAbis.ts
// Do not edit manually - regenerate after deployment

export const deployedContracts = ${JSON.stringify(allDeployments, null, 2)} as const;

export type ChainId = ${chainIds.map((id) => `"${id}"`).join(" | ")};

`;

  // Add contract name types for each chain (prefix with Chain to avoid numeric type names)
  for (const chainId of chainIds) {
    const contractNames = Object.keys(allDeployments[chainId]);
    if (contractNames.length > 0) {
      const safeName = `Chain${chainId.replace(/-/g, "")}`;
      content += `export type ${safeName}ContractName = ${contractNames
        .map((n) => `"${n}"`)
        .join(" | ")};\n`;
    }
  }

  content += `
// Helper types
export type ContractDeployment = {
  address: \`0x\${string}\`;
  abi: readonly unknown[];
};

// Helper to access deployments with proper typing
function getChainDeployments(chainId: ChainId): Record<string, { address: string; abi: unknown[] }> | undefined {
  return (deployedContracts as unknown as Record<string, Record<string, { address: string; abi: unknown[] }>>)[chainId];
}

export function getContract(chainId: ChainId, contractName: string): ContractDeployment {
  const chain = getChainDeployments(chainId);
  const contract = chain?.[contractName];
  if (!contract) {
    throw new Error(\`Contract \${contractName} not found on chain \${chainId}\`);
  }
  return { address: contract.address as \`0x\${string}\`, abi: contract.abi as readonly unknown[] };
}

export function getContractAddress(chainId: ChainId, contractName: string): \`0x\${string}\` {
  return getContract(chainId, contractName).address;
}
`;

  return content;
}

export function generateTsAbis(): boolean {
  console.log("\n📦 Generating TypeScript ABIs...\n");

  if (!existsSync(BROADCAST_DIR)) {
    console.log("❌ No broadcast directory found. Run deployment first.");
    return false;
  }

  // Find all chain directories in Deploy.s.sol broadcast
  const deployBroadcastDir = join(BROADCAST_DIR, "Deploy.s.sol");
  if (!existsSync(deployBroadcastDir)) {
    console.log("❌ No deployment broadcasts found.");
    return false;
  }

  const chainDirs = readdirSync(deployBroadcastDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);

  if (chainDirs.length === 0) {
    console.log("❌ No deployment records found.");
    return false;
  }

  const allDeployments: AllDeployments = {};

  for (const chainId of chainDirs) {
    console.log(`Processing chain ${chainId}...`);

    const runFilePath = findLatestRunFile(chainId);
    if (!runFilePath) {
      console.log(`  ⚠️  No run files found for chain ${chainId}`);
      continue;
    }

    const runData: BroadcastRun = JSON.parse(
      readFileSync(runFilePath, "utf-8"),
    );
    const deployments: ChainDeployments = {};

    for (const tx of runData.transactions || []) {
      if (tx.transactionType !== "CREATE" || !tx.contractName) continue;

      const artifact = loadArtifact(tx.contractName);
      if (!artifact) {
        console.log(`  ⚠️  Artifact not found for ${tx.contractName}`);
        continue;
      }

      deployments[tx.contractName] = {
        address: tx.contractAddress,
        abi: artifact.abi,
      };

      console.log(`  ✅ ${tx.contractName}: ${tx.contractAddress}`);
    }

    if (Object.keys(deployments).length > 0) {
      allDeployments[chainId] = deployments;
    }
  }

  if (Object.keys(allDeployments).length === 0) {
    console.log("\n❌ No deployments found to export.");
    return false;
  }

  // Generate TypeScript file
  const tsContent = generateTsContent(allDeployments);

  // Write to contracts package
  const contractsOutputPath = join(process.cwd(), "deployedContracts.ts");
  writeFileSync(contractsOutputPath, tsContent);
  console.log(`\n✅ Generated: ${contractsOutputPath}`);

  // Also write to React Native app's lib/blockchain directory
  const appOutputPath = join(
    process.cwd(),
    "..",
    "..",
    "lib",
    "blockchain",
    "deployedContracts.ts",
  );
  writeFileSync(appOutputPath, tsContent);
  console.log(`✅ Generated: ${appOutputPath}\n`);

  return true;
}

// Run if executed directly
if (import.meta.main) {
  generateTsAbis();
}
