// Auto-generated by generateTsAbis.ts
// Do not edit manually - regenerate after deployment

export const deployedContracts = {
  "84532": {
    "NFCPaymentVerifier": {
      "address": "0xe1247d0F2F2bd41c4bA1f10bC2D1394F1462Ca13",
      "abi": [
        {
          "type": "constructor",
          "inputs": [
            {
              "name": "usdc",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "usdt",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "initialOwner",
              "type": "address",
              "internalType": "address"
            }
          ],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "claimPayment",
          "inputs": [
            {
              "name": "token",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "merchant",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "customer",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "amount",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "nonce",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "deadline",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "signature",
              "type": "bytes",
              "internalType": "bytes"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "eip712Domain",
          "inputs": [],
          "outputs": [
            {
              "name": "fields",
              "type": "bytes1",
              "internalType": "bytes1"
            },
            {
              "name": "name",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "version",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "chainId",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "verifyingContract",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "salt",
              "type": "bytes32",
              "internalType": "bytes32"
            },
            {
              "name": "extensions",
              "type": "uint256[]",
              "internalType": "uint256[]"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "hashPaymentAuthorization",
          "inputs": [
            {
              "name": "token",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "merchant",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "customer",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "amount",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "nonce",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "deadline",
              "type": "uint256",
              "internalType": "uint256"
            }
          ],
          "outputs": [
            {
              "name": "",
              "type": "bytes32",
              "internalType": "bytes32"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "owner",
          "inputs": [],
          "outputs": [
            {
              "name": "",
              "type": "address",
              "internalType": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "renounceOwnership",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "setTokenSupport",
          "inputs": [
            {
              "name": "token",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "supported",
              "type": "bool",
              "internalType": "bool"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "supportedTokens",
          "inputs": [
            {
              "name": "token",
              "type": "address",
              "internalType": "address"
            }
          ],
          "outputs": [
            {
              "name": "supported",
              "type": "bool",
              "internalType": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "transferOwnership",
          "inputs": [
            {
              "name": "newOwner",
              "type": "address",
              "internalType": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "usedNonces",
          "inputs": [
            {
              "name": "customer",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "nonce",
              "type": "uint256",
              "internalType": "uint256"
            }
          ],
          "outputs": [
            {
              "name": "used",
              "type": "bool",
              "internalType": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "event",
          "name": "EIP712DomainChanged",
          "inputs": [],
          "anonymous": false
        },
        {
          "type": "event",
          "name": "OwnershipTransferred",
          "inputs": [
            {
              "name": "previousOwner",
              "type": "address",
              "indexed": true,
              "internalType": "address"
            },
            {
              "name": "newOwner",
              "type": "address",
              "indexed": true,
              "internalType": "address"
            }
          ],
          "anonymous": false
        },
        {
          "type": "event",
          "name": "PaymentClaimed",
          "inputs": [
            {
              "name": "customer",
              "type": "address",
              "indexed": true,
              "internalType": "address"
            },
            {
              "name": "merchant",
              "type": "address",
              "indexed": true,
              "internalType": "address"
            },
            {
              "name": "token",
              "type": "address",
              "indexed": true,
              "internalType": "address"
            },
            {
              "name": "amount",
              "type": "uint256",
              "indexed": false,
              "internalType": "uint256"
            },
            {
              "name": "nonce",
              "type": "uint256",
              "indexed": false,
              "internalType": "uint256"
            }
          ],
          "anonymous": false
        },
        {
          "type": "event",
          "name": "TokenSupportUpdated",
          "inputs": [
            {
              "name": "token",
              "type": "address",
              "indexed": true,
              "internalType": "address"
            },
            {
              "name": "supported",
              "type": "bool",
              "indexed": false,
              "internalType": "bool"
            }
          ],
          "anonymous": false
        },
        {
          "type": "error",
          "name": "InvalidShortString",
          "inputs": []
        },
        {
          "type": "error",
          "name": "InvalidSignature",
          "inputs": []
        },
        {
          "type": "error",
          "name": "NonceAlreadyUsed",
          "inputs": []
        },
        {
          "type": "error",
          "name": "OwnableInvalidOwner",
          "inputs": [
            {
              "name": "owner",
              "type": "address",
              "internalType": "address"
            }
          ]
        },
        {
          "type": "error",
          "name": "OwnableUnauthorizedAccount",
          "inputs": [
            {
              "name": "account",
              "type": "address",
              "internalType": "address"
            }
          ]
        },
        {
          "type": "error",
          "name": "ReentrancyGuardReentrantCall",
          "inputs": []
        },
        {
          "type": "error",
          "name": "SignatureExpired",
          "inputs": []
        },
        {
          "type": "error",
          "name": "StringTooLong",
          "inputs": [
            {
              "name": "str",
              "type": "string",
              "internalType": "string"
            }
          ]
        },
        {
          "type": "error",
          "name": "TokenNotSupported",
          "inputs": []
        },
        {
          "type": "error",
          "name": "TransferFailed",
          "inputs": []
        }
      ]
    }
  }
} as const;

export type ChainId = "84532";

export type Chain84532ContractName = "NFCPaymentVerifier";

// Helper types
export type ContractDeployment = {
  address: `0x${string}`;
  abi: readonly unknown[];
};

// Helper to access deployments with proper typing
function getChainDeployments(chainId: ChainId): Record<string, { address: string; abi: unknown[] }> | undefined {
  return (deployedContracts as unknown as Record<string, Record<string, { address: string; abi: unknown[] }>>)[chainId];
}

export function getContract(chainId: ChainId, contractName: string): ContractDeployment {
  const chain = getChainDeployments(chainId);
  const contract = chain?.[contractName];
  if (!contract) {
    throw new Error(`Contract ${contractName} not found on chain ${chainId}`);
  }
  return { address: contract.address as `0x${string}`, abi: contract.abi as readonly unknown[] };
}

export function getContractAddress(chainId: ChainId, contractName: string): `0x${string}` {
  return getContract(chainId, contractName).address;
}
